config/routes.rb
Rails.application.routes.draw do
  root 'tweets#index'
  get 'tweets/new'
  post '/tweets',to: 'tweets#create'

  get 'comments/new'
  post '/comments',to: 'comments#create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comments = Comment.new
  end

  def create
    @comments = Comment.new(comment: params[:comment][:comment],tweet_id: params[:comment][:tweet_id])
    if @comments.save
      puts "OK create"
      redirect_to root_path
    else
      puts "NO create"
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
    @cerect_tweet = Tweet.find_by(id: params[:tweet_id])
    @page = params[:page]
    
  end

  def new
    @tweets = Tweet.new
  end

  def create
    @tweets = Tweet.new(tweet: params[:tweet][:tweet])
    if @tweets.save
      puts "OK create"
      redirect_to root_path
    else
      puts "NO create"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/comments/new.html.erb
<div class="comment_new_contaner">
  <%= form_with model:@comments,local:true,url:'/comments' do |form| %>
    <label><%= form.text_area :comment %></label>
    <label><%= form.hidden_field :tweet_id,:value => params[:tweet_id] %></label>
    <label><%= form.submit %></label>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Comment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/_index.html.erb
<% comments.each do |comment| %>
  <p class="comment"><%= comment.comment %></p>

<% end %>
<%= paginate comments,params:{tweet_id: tweet_id},remote:true%>

app/views/tweets/index.html.erb
<div class="container">
<%= link_to(tweets_new_path) do %>
  <button>New Tweet</button>
<% end %>
<!-- <a href="#">a</a> -->
<% @tweets.each do |tweet| %>
<div class="tweet_container">
<div class="tweet_child_container">

  <p class="tweet"><%= tweet.tweet %></p>
  <div class="comment_container">

  <div id="tweet_<%= tweet.id %>" >
    <%= render partial: 'index',locals:{comments:tweet.comments.page(params[:page]).per(3),tweet_id:tweet.id}%>
  </div>


  <%= link_to(comments_new_path(:tweet_id => tweet.id)) do%>
    <button>New Comment</button>
  <% end %>
  </div>
</div>
</div>
<% end %>
</div>
<!-- <script>
  $('a').on('click',function(){
    console.log('hello');
    setTimeout(function(){
    },1000);
  });
</script> -->

app/views/tweets/index.js.erb
$("#tweet_<%= @cerect_tweet.id %>").html('<%= j(render partial:"index",locals:{comments:@cerect_tweet.comments.page(@page).per(3),tweet_id:@cerect_tweet.id}) %>');

app/views/tweets/new.html.erb
<div class="tweet_new_contaner">
  <%= form_with model:@tweets,local:true do |form| %>
    <label><%= form.text_area :tweet %></label>
    <label><%= form.submit %></label>
  <% end %>
</div>